apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spokes
  namespace: rhacm-apps
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - "spoke1"
      - "spoke2"