apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: spoke1
  namespace: rhacm-apps
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels: 
      name: "s1-aws-tn"
  clusterReplicas: 1
