apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: volsync-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - list:
      elements:
      - cluster: spoke1
        url: https://api.s1-aws-tn.dev09.red-chesterfield.com:6443
      - cluster: spoke2
        url: https://api.s2-aws-tn.dev09.red-chesterfield.com:6443
  template:
    metadata:
      name: '{{cluster}}-volsync-config'
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/thuyn-581/sleeping-through-disasters.git
        targetRevision: base-config
        path: 'config/scribe-config/{{cluster}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
        - Validate=true
        - CreateNamespace=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      destination:
        server: '{{url}}'
        namespace: uploader-app
