apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: volsync-configs-application
  namespace: rhacm-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - volsync-configs-spoke1
      - volsync-configs-spoke2
