apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uploader-pvc 
  namespace: uploader-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: Clone 
    destinationPVC: uploader-pvc
    sshKeys: scribe-key
