apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uploader-pvc 
  namespace: uploader-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourcePVC: uploader-pvc
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-key
    address: a5fffb912c76e41678a8a858e6c480d6-9dc251a918d99ade.elb.us-east-1.amazonaws.com
    copyMethod: Snapshot
