apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uploader-pvc 
  namespace: rhacm-apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourcePVC: uploader-pvc
  trigger:
    schedule: "*/2 * * * *"
  rsync:
    sshKeys: scribe-key
    address: volsync-rsync-dst-uploader-pvc.rhacm-apps.svc.clusterset.local
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]